"""
ISAA - the agent loop.

THE SAME LOOP AS EVERY OTHER AGENT
    call the model -> did it ask for a tool? -> run it -> append -> repeat,
    until it asks for nothing. Better tools, same fifteen lines.

THE ONE THING THAT IS DIFFERENT HERE
    The loop RECORDS every tool call and its result. The model never gets to
    assert a number on its own authority - the transcript of tool results is
    kept separately, so eval E-2 can trace every figure in an answer back to
    something the database actually returned.

    If claims were generated by the model instead, "grounded" would mean "the
    model said it was grounded", which is worth nothing.

WHAT THE SYSTEM PROMPT CANNOT DO
    It says: no verdicts, never guess, always cite. Those are instructions, and
    a model can ignore instructions - you have watched one do exactly that.
    So the rules are also tested (evals E-1 to E-3) and the dangerous ones are
    enforced in code and in the tool shapes, not only in the prompt.

    python -m isaa.loop "is this fund risky?" --fund 119507
"""
from __future__ import annotations

import json
import re
import sys
import time
from dataclasses import dataclass, field

import groq

from config import GROQ_MODEL
from constants import FORECAST_PATTERNS
from isaa.tools import DECLARATIONS, NUMERIC_TOOLS, TOOLS

MAX_STEPS = 8
TEMPERATURE = 0
RATE_LIMIT_WAIT_SECONDS = 20

# How long we are willing to sit waiting out a rate limit.
#
# A person waiting for a chat reply will not wait three minutes - they will
# assume it is broken, which is exactly what happened. A batch job has nobody
# waiting and should wait as long as it takes.
INTERACTIVE_RETRY_BUDGET = 15.0     # a user is watching
BATCH_RETRY_BUDGET = 600.0          # evals and jobs

SYSTEM = """You are Isaa, an assistant that helps people understand Indian mutual funds.

WHAT YOU DO
- Explain funds, terms and the Finishh Meter in plain English.
- Give facts, context and risks so the person can decide for themselves.

WHAT YOU MUST NEVER DO
- Never say whether to buy, sell or hold. Not even with a disclaimer.
- Never predict a future return or say a fund "will" do anything.
- Never state a number you did not receive from a tool in this conversation.
  If you do not have it, say you do not have it.
- Never take a number out of search_concepts. That tool returns explanations
  only. Numbers come from get_fund_details and get_meter.

WHAT YOU ACTUALLY HOLD ABOUT A FUND
  Only these: name, fund house, category, sub-category, latest NAV and its date,
  how far the price history goes back, how many price points there are, and the
  Finishh Meter for 1, 3 and 5 years.

  You do NOT hold: AUM, expense ratio, exit load, fund manager, holdings,
  sector allocation, portfolio, Sharpe ratio, alpha, beta, standard deviation,
  benchmark returns, ratings, or anything else.

  If asked for something not on the first list, say plainly that you do not
  have it.

WHAT YOU KNOW ABOUT FINANCIAL TERMS
  Only what search_concepts returns. If that tool comes back empty, you do NOT
  know the term - say so. Do not define it from memory. A confident wrong
  definition of a financial term is worse than admitting you do not have it. Do not answer it from memory or from general knowledge, even if you
  believe you know it. A number that did not come from a tool in THIS
  conversation is a fabrication, however plausible it sounds.

HOW TO ANSWER
- ANSWER FIRST. Open with one plain sentence that answers the question. Then
  supporting detail if it helps. Never open with a table or a list of figures -
  the point of this product is that a beginner meets an explanation before a
  wall of numbers.
- Short. Aim for about 80 words. A table is allowed only when comparing across
  holding periods, and only after the opening sentence.
- Use markdown for structure (bold, tables, short lists). It is rendered.
- Say where a figure came from and as of when.
- WORDING OF METER FIGURES. The meter counts past periods. It says nothing
  about probability. These are banned, without exception:
      "chance of", "probability of", "likely to", "expected return",
      "risk of losing X%", "you could get", "will return"
  Correct phrasing:
      "46% of past 1-year periods ended in a loss"
      "in 3 of every 4 past 3-year periods it returned over 10% a year"
  Wrong, even though it sounds similar:
      "a 46% chance of loss"        <- we have no probability
      "moderate chance of loss"     <- same problem in words
- If asked what to buy, explain what the data shows and what to weigh, and say
  plainly that you cannot advise.
- Keep financial terms and disclaimers in English even if the user writes in
  another language."""


RETRY_AFTER_RE = re.compile(r"try again in ([\d.]+)(m)?([\d.]+)?s")


def _retry_delay(exc) -> float:
    """Groq states exactly how long to wait. Guessing is worse than reading it.

    Its two limits need very different waits: tokens-per-minute clears in under
    a second, tokens-per-day can need minutes. A fixed 20s guess is too long for
    one and far too short for the other."""
    match = RETRY_AFTER_RE.search(str(exc))
    if not match:
        return RATE_LIMIT_WAIT_SECONDS
    minutes = float(match.group(1)) if match.group(2) else 0.0
    seconds = float(match.group(3) or (0.0 if match.group(2) else match.group(1)))
    return minutes * 60 + seconds + 1.0          # a second of headroom


class RateLimited(Exception):
    """Out of quota and not worth waiting for on this request."""

    def __init__(self, retry_after: float):
        self.retry_after = retry_after
        super().__init__(f"rate limited, retry in about {retry_after:.0f}s")


def _call_model(client, messages, model: str = GROQ_MODEL,
                budget: float = INTERACTIVE_RETRY_BUDGET):
    """Retries within a time BUDGET rather than a count.

    A count is the wrong unit: six retries can mean six seconds or six minutes
    depending on which limit was hit. What the caller actually cares about is
    how long it is prepared to wait."""
    spent, attempt = 0.0, 0
    while True:
        try:
            return client.chat.completions.create(
                model=model, messages=messages, tools=DECLARATIONS,
                tool_choice="auto", temperature=TEMPERATURE,
            )
        except groq.RateLimitError as exc:
            wait = _retry_delay(exc)
            if spent + wait > budget:
                raise RateLimited(wait) from exc
            print(f"      [rate limited: waiting {wait:.0f}s]", flush=True)
            time.sleep(wait)
            spent += wait
        except groq.InternalServerError:
            wait = 2 ** attempt
            if spent + wait > budget:
                raise
            time.sleep(wait)
            spent += wait
            attempt += 1


def forecast_wording(text: str) -> str | None:
    """Return the banned phrase found in an answer, or None.

    Normalises curly apostrophes and non-breaking hyphens first - models write
    "don’t" and "short‑term", and a checker that misses those is a checker
    that quietly passes everything."""
    clean = (text.lower()
             .replace("\u2019", "'").replace("\u2011", "-")
             .replace("\u2013", "-").replace("\u2014", "-"))
    for pattern in FORECAST_PATTERNS:
        match = re.search(pattern, clean)
        if match:
            return match.group(0)
    return None


@dataclass
class Turn:
    answer: str = ""
    rewritten_for_wording: bool = False
    ungrounded_explanation: bool = False
    tool_calls: list[dict] = field(default_factory=list)
    numeric_results: list[dict] = field(default_factory=list)
    steps: int = 0
    seconds: float = 0.0
    stopped_early: bool = False


def _client() -> groq.Groq:
    import os
    from dotenv import load_dotenv
    load_dotenv(); load_dotenv(".env.local", override=True)
    return groq.Groq(api_key=os.getenv("GROQ_API_KEY"))


def ask(question: str, fund_code: str | None = None,
        history: list | None = None, model: str = GROQ_MODEL,
        budget: float = INTERACTIVE_RETRY_BUDGET) -> Turn:
    """One question. `fund_code` is the page the user is on (rule I-9)."""
    started = time.time()
    turn = Turn()

    system = SYSTEM
    if fund_code:
        system += (f"\n\nCONTEXT: the user is looking at the fund with "
                   f"source_code {fund_code}. If they say 'this fund' or 'it', "
                   f"they mean that one. You still have to look it up.")

    messages = [{"role": "system", "content": system}]
    messages.extend(history or [])
    messages.append({"role": "user", "content": question})

    client = _client()
    for step in range(1, MAX_STEPS + 1):
        turn.steps = step
        response = _call_model(client, messages, model, budget)
        reply = response.choices[0].message
        calls = reply.tool_calls or []

        if not calls:
            answer = reply.content or ""

            # The prompt asks for correct wording. A model can ignore a prompt -
            # this one did, repeatedly. So the rule is enforced here instead.
            banned = forecast_wording(answer)
            if banned:
                messages.append(reply)
                messages.append({"role": "user", "content": (
                    f'Your answer used the phrase "{banned}". The Finishh Meter '
                    f'counts what happened in past periods and says nothing about '
                    f'probability. Rewrite the same answer without any wording '
                    f'that suggests a forecast or a likelihood. Say "X% of past '
                    f'N-year periods ended in ..." instead. Keep the facts and '
                    f'numbers exactly the same.')})
                retry = _call_model(client, messages, model, budget)
                rewritten = retry.choices[0].message.content or ""
                if rewritten and not forecast_wording(rewritten):
                    answer = rewritten
                    turn.rewritten_for_wording = True

            # If every concept search came back empty and no database tool ran,
            # then anything explanatory in this answer came from the model's
            # training data, not from our verified layer. That is rule I-2, and
            # a plausible-sounding wrong definition on a finance site is worse
            # than saying nothing.
            searched = [c for c in turn.tool_calls if c["tool"] == "search_concepts"]
            found_nothing = searched and all(not c["result"] for c in searched)
            used_database = any(c["tool"] in NUMERIC_TOOLS or c["tool"] == "find_fund"
                                for c in turn.tool_calls)
            if found_nothing and not used_database:
                turn.ungrounded_explanation = True
                asked = searched[-1]["args"].get("question", "that")
                answer = (
                    f"I don't have a written explanation for that in my notes, "
                    f"so I can't answer it reliably.\n\n"
                    f"I only explain terms I have verified material for - things "
                    f"like NAV, expense ratio, CAGR, XIRR, SIP, exit load, "
                    f"drawdown, risk levels and the Finishh Meter. Ask me about "
                    f"any of those, or about a specific fund on this page."
                )

            turn.answer = answer
            turn.seconds = time.time() - started
            return turn

        messages.append(reply)
        for call in calls:
            name = call.function.name
            args = json.loads(call.function.arguments or "{}")
            function = TOOLS.get(name)
            try:
                result = function(**args) if function else {"error": f"no tool {name}"}
            except Exception as exc:
                result = {"error": f"{type(exc).__name__}: {exc}"}

            turn.tool_calls.append({"tool": name, "args": args, "result": result})
            if name in NUMERIC_TOOLS and isinstance(result, dict) and "error" not in result:
                turn.numeric_results.append(result)

            messages.append({"role": "tool", "tool_call_id": call.id,
                             "name": name, "content": json.dumps(result, default=str)})

    turn.stopped_early = True
    turn.answer = "I could not finish working that out. Please try asking more simply."
    turn.seconds = time.time() - started
    return turn


if __name__ == "__main__":
    args = sys.argv[1:]
    code = None
    if "--fund" in args:
        i = args.index("--fund"); code = args[i + 1]; args = args[:i] + args[i + 2:]
    question = " ".join(args) or "what is an expense ratio?"

    result = ask(question, fund_code=code)
    print(f"\nQ: {question}\n")
    for call in result.tool_calls:
        print(f"   -> {call['tool']}({call['args']})")
    print(f"\nA: {result.answer}\n")
    print(f"   {result.steps} steps, {result.seconds:.1f}s")
